# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from open_banking_account_and_transaction_python_sdk import OpenBankingAccountAndTransaction

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        openbankingaccountandtransaction = OpenBankingAccountAndTransaction(
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',,
        
            client_id = 'YOUR_CLIENT_ID',
            client_secret = 'YOUR_CLIENT_SECRET',
        )
        self.assertIsNotNone(openbankingaccountandtransaction)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
