# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.identification2 import Identification2
from open_banking_account_and_transaction_python_sdk.type.name1 import Name1
from open_banking_account_and_transaction_python_sdk.type.ob_postal_address6 import OBPostalAddress6

class RequiredOBBranchAndFinancialInstitutionIdentification62(TypedDict):
    pass

class OptionalOBBranchAndFinancialInstitutionIdentification62(TypedDict, total=False):
    Identification: Identification2

    Name: Name1

    PostalAddress: OBPostalAddress6

    # Name of the identification scheme, in a coded form as published in an external list.
    SchemeName: str

class OBBranchAndFinancialInstitutionIdentification62(RequiredOBBranchAndFinancialInstitutionIdentification62, OptionalOBBranchAndFinancialInstitutionIdentification62):
    pass
