# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.account_id import AccountId
from open_banking_account_and_transaction_python_sdk.type.beneficiary_id import BeneficiaryId
from open_banking_account_and_transaction_python_sdk.type.ob_beneficiary_type1_code import OBBeneficiaryType1Code
from open_banking_account_and_transaction_python_sdk.type.ob_supplementary_data1 import OBSupplementaryData1
from open_banking_account_and_transaction_python_sdk.type.reference import Reference

class RequiredOBBeneficiary5Basic(TypedDict):
    pass

class OptionalOBBeneficiary5Basic(TypedDict, total=False):
    AccountId: AccountId

    BeneficiaryId: BeneficiaryId

    BeneficiaryType: OBBeneficiaryType1Code

    Reference: Reference

    SupplementaryData: OBSupplementaryData1

class OBBeneficiary5Basic(RequiredOBBeneficiary5Basic, OptionalOBBeneficiary5Basic):
    pass
