# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOBBankTransactionCodeStructure1(TypedDict):
    # Specifies the family within a domain.
    Code: str

    # Specifies the sub-product family within a specific family.
    SubCode: str

class OptionalOBBankTransactionCodeStructure1(TypedDict, total=False):
    pass

class OBBankTransactionCodeStructure1(RequiredOBBankTransactionCodeStructure1, OptionalOBBankTransactionCodeStructure1):
    pass
