# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_error1 import OBError1

class RequiredOBErrorResponse1(TypedDict):
    # High level textual error code, to help categorize the errors.
    Code: str

    Errors: typing.List[OBError1]

    # Brief Error message, e.g., 'There is something wrong with the request parameters provided'
    Message: str

class OptionalOBErrorResponse1(TypedDict, total=False):
    # A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.
    Id: str

class OBErrorResponse1(RequiredOBErrorResponse1, OptionalOBErrorResponse1):
    pass
