# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOBPartyRelationships1Account(TypedDict):
    # Unique identification as assigned by the ASPSP to uniquely identify the related resource.
    Id: str

    # Absolute URI to the related resource.
    Related: str

class OptionalOBPartyRelationships1Account(TypedDict, total=False):
    pass

class OBPartyRelationships1Account(RequiredOBPartyRelationships1Account, OptionalOBPartyRelationships1Account):
    pass
