# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_other_fees_charges_item_fee_charge_cap import OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeCap
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_other_fees_charges_item_fee_charge_detail import OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeDetail
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_other_fees_charges_item_other_tariff_type import OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemOtherTariffType

class RequiredOBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItem(TypedDict):
    FeeChargeDetail: OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeDetail

class OptionalOBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItem(TypedDict, total=False):
    FeeChargeCap: OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeCap

    OtherTariffType: OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemOtherTariffType

    # Name of the tariff
    TariffName: str

    # TariffType which defines the fee and charges.
    TariffType: str

class OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItem(RequiredOBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItem, OptionalOBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItem):
    pass
