# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_account6 import OBAccount6

class RequiredOBReadAccount6Data(TypedDict):
    pass

class OptionalOBReadAccount6Data(TypedDict, total=False):
    Account: typing.List[OBAccount6]

class OBReadAccount6Data(RequiredOBReadAccount6Data, OptionalOBReadAccount6Data):
    pass
