# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_transaction6 import OBTransaction6

class RequiredOBReadDataTransaction6(TypedDict):
    pass

class OptionalOBReadDataTransaction6(TypedDict, total=False):
    Transaction: typing.List[OBTransaction6]

class OBReadDataTransaction6(RequiredOBReadDataTransaction6, OptionalOBReadDataTransaction6):
    pass
