# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_read_consent1_data import OBReadConsent1Data

class RequiredOBReadConsent1(TypedDict):
    Data: OBReadConsent1Data

    # The Risk section is sent by the initiating party to the ASPSP. It is used to specify additional details for risk scoring for Account Info.
    Risk: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class OptionalOBReadConsent1(TypedDict, total=False):
    pass

class OBReadConsent1(RequiredOBReadConsent1, OptionalOBReadConsent1):
    pass
