# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_interest_calculation_method1_code import OBInterestCalculationMethod1Code
from open_banking_account_and_transaction_python_sdk.type.ob_other_code_type10 import OBOtherCodeType10
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_credit_interest_tier_band_set_item_notes import OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemNotes
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_credit_interest_tier_band_set_item_tier_band import OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemTierBand

class RequiredOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(TypedDict):
    # Describes whether accrued interest is payable only to the BCA or to another bank account
    Destination: str

    TierBand: OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemTierBand

    # The methodology of how credit interest is paid/applied. It can be:- 1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases. 2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance. 3. Whole The same interest rate is applied irrespective of the product holder's account balance
    TierBandMethod: str

class OptionalOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(TypedDict, total=False):
    CalculationMethod: OBInterestCalculationMethod1Code

    Notes: OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemNotes

    OtherCalculationMethod: OBOtherCodeType10

    OtherDestination: OBOtherCodeType10

class OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(RequiredOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem, OptionalOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem):
    pass
