# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_other_code_type10 import OBOtherCodeType10
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_product_details_notes import OBReadProduct2DataProductItemOtherProductTypeProductDetailsNotes
from open_banking_account_and_transaction_python_sdk.type.ob_read_product2_data_product_item_other_product_type_product_details_segment import OBReadProduct2DataProductItemOtherProductTypeProductDetailsSegment

class RequiredOBReadProduct2DataProductItemOtherProductTypeProductDetails(TypedDict):
    pass

class OptionalOBReadProduct2DataProductItemOtherProductTypeProductDetails(TypedDict, total=False):
    # The length/duration of the fee free period
    FeeFreeLength: int

    # The unit of period (days, weeks, months etc.) of the promotional length
    FeeFreeLengthPeriod: str

    # The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
    MonthlyMaximumCharge: str

    Notes: OBReadProduct2DataProductItemOtherProductTypeProductDetailsNotes

    OtherSegment: OBOtherCodeType10

    Segment: OBReadProduct2DataProductItemOtherProductTypeProductDetailsSegment

class OBReadProduct2DataProductItemOtherProductTypeProductDetails(RequiredOBReadProduct2DataProductItemOtherProductTypeProductDetails, OptionalOBReadProduct2DataProductItemOtherProductTypeProductDetails):
    pass
