# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.links import Links
from open_banking_account_and_transaction_python_sdk.type.meta import Meta
from open_banking_account_and_transaction_python_sdk.type.ob_read_scheduled_payment3_data import OBReadScheduledPayment3Data

class RequiredOBReadScheduledPayment3(TypedDict):
    Data: OBReadScheduledPayment3Data

class OptionalOBReadScheduledPayment3(TypedDict, total=False):
    Links: Links

    Meta: Meta

class OBReadScheduledPayment3(RequiredOBReadScheduledPayment3, OptionalOBReadScheduledPayment3):
    pass
