# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.ob_beneficiary5 import OBBeneficiary5

class RequiredOBReadBeneficiary5Data(TypedDict):
    pass

class OptionalOBReadBeneficiary5Data(TypedDict, total=False):
    Beneficiary: typing.List[OBBeneficiary5]

class OBReadBeneficiary5Data(RequiredOBReadBeneficiary5Data, OptionalOBReadBeneficiary5Data):
    pass
