# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.obbca_data1_credit_interest_tier_band_set_item_tier_band_item_notes import OBBCAData1CreditInterestTierBandSetItemTierBandItemNotes
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_credit_interest_tier_band_set_item_tier_band_item_other_application_frequency import OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherApplicationFrequency
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_credit_interest_tier_band_set_item_tier_band_item_other_bank_interest_type import OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherBankInterestType
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_credit_interest_tier_band_set_item_tier_band_item_other_calculation_frequency import OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherCalculationFrequency

class RequiredOBBCAData1CreditInterestTierBandSetItemTierBandItem(TypedDict):
    # The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.   Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
    AER: str

    # How often is interest applied to the BCA for this tier/band i.e. how often the financial institution pays accumulated interest to the customer's BCA.
    ApplicationFrequency: str

    # Type of interest rate, Fixed or Variable
    FixedVariableInterestRateType: str

    # Minimum deposit value for which the credit interest tier applies.
    TierValueMinimum: str

class OptionalOBBCAData1CreditInterestTierBandSetItemTierBandItem(TypedDict, total=False):
    # Bank Interest for the BCA product
    BankInterestRate: str

    # Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the BCA.
    BankInterestRateType: str

    # How often is credit interest calculated for the account.
    CalculationFrequency: str

    # Amount on which Interest applied.
    DepositInterestAppliedCoverage: str

    # Unique and unambiguous identification of a  Tier Band for a BCA.
    Identification: str

    Notes: OBBCAData1CreditInterestTierBandSetItemTierBandItemNotes

    OtherApplicationFrequency: OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherApplicationFrequency

    OtherBankInterestType: OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherBankInterestType

    OtherCalculationFrequency: OBBCAData1CreditInterestTierBandSetItemTierBandItemOtherCalculationFrequency

    # Maximum deposit value for which the credit interest tier applies.
    TierValueMaximum: str

class OBBCAData1CreditInterestTierBandSetItemTierBandItem(RequiredOBBCAData1CreditInterestTierBandSetItemTierBandItem, OptionalOBBCAData1CreditInterestTierBandSetItemTierBandItem):
    pass
