# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.obbca_data1_product_details_notes import OBBCAData1ProductDetailsNotes
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_product_details_segment import OBBCAData1ProductDetailsSegment

class RequiredOBBCAData1ProductDetails(TypedDict):
    pass

class OptionalOBBCAData1ProductDetails(TypedDict, total=False):
    # The length/duration of the fee free period
    FeeFreeLength: typing.Union[int, float]

    # The unit of period (days, weeks, months etc.) of the promotional length
    FeeFreeLengthPeriod: str

    Notes: OBBCAData1ProductDetailsNotes

    Segment: OBBCAData1ProductDetailsSegment

class OBBCAData1ProductDetails(RequiredOBBCAData1ProductDetails, OptionalOBBCAData1ProductDetails):
    pass
