# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from open_banking_account_and_transaction_python_sdk.type.obbca_data1_overdraft_overdraft_tier_band_set_item_notes import OBBCAData1OverdraftOverdraftTierBandSetItemNotes
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_overdraft_overdraft_tier_band_set_item_overdraft_fees_charges import OBBCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesCharges
from open_banking_account_and_transaction_python_sdk.type.obbca_data1_overdraft_overdraft_tier_band_set_item_overdraft_tier_band import OBBCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBand

class RequiredOBBCAData1OverdraftOverdraftTierBandSetItem(TypedDict):
    OverdraftTierBand: OBBCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBand

    # The methodology of how overdraft is charged. It can be: 'Whole'  Where the same charge/rate is applied to the entirety of the overdraft balance (where charges are applicable).  'Tiered' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount tiers defined by the lending financial organisation 'Banded' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount bands defined by a government organisation.
    TierBandMethod: str

class OptionalOBBCAData1OverdraftOverdraftTierBandSetItem(TypedDict, total=False):
    # Indicates if the Overdraft is authorised (Y) or unauthorised (N)
    AuthorisedIndicator: bool

    # When a customer exceeds their credit limit, a financial institution will not charge the customer unauthorised overdraft charges if they do not exceed by more than the buffer amount. Note: Authorised overdraft charges may still apply.
    BufferAmount: str

    # Unique and unambiguous identification of a  Tier Band for a overdraft product.
    Identification: str

    Notes: OBBCAData1OverdraftOverdraftTierBandSetItemNotes

    OverdraftFeesCharges: OBBCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesCharges

    # An overdraft can either be 'committed' which means that the facility cannot be withdrawn without reasonable notification before it's agreed end date, or 'on demand' which means that the financial institution can demand repayment at any point in time.
    OverdraftType: str

class OBBCAData1OverdraftOverdraftTierBandSetItem(RequiredOBBCAData1OverdraftOverdraftTierBandSetItem, OptionalOBBCAData1OverdraftOverdraftTierBandSetItem):
    pass
