# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.identification2 import Identification2
from open_banking_account_and_transaction_python_sdk.pydantic.name1 import Name1
from open_banking_account_and_transaction_python_sdk.pydantic.ob_postal_address6 import OBPostalAddress6

class OBBranchAndFinancialInstitutionIdentification61(BaseModel):
    identification: typing.Optional[Identification2] = Field(None, alias='Identification')

    name: typing.Optional[Name1] = Field(None, alias='Name')

    postal_address: typing.Optional[OBPostalAddress6] = Field(None, alias='PostalAddress')

    # Name of the identification scheme, in a coded form as published in an external list.
    scheme_name: typing.Optional[str] = Field(None, alias='SchemeName')
    class Config:
        arbitrary_types_allowed = True
