# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_credit_interest import OBReadProduct2DataProductItemOtherProductTypeCreditInterest
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_loan_interest import OBReadProduct2DataProductItemOtherProductTypeLoanInterest
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_other_fees_charges import OBReadProduct2DataProductItemOtherProductTypeOtherFeesCharges
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_overdraft import OBReadProduct2DataProductItemOtherProductTypeOverdraft
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_product_details import OBReadProduct2DataProductItemOtherProductTypeProductDetails
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_repayment import OBReadProduct2DataProductItemOtherProductTypeRepayment
from open_banking_account_and_transaction_python_sdk.pydantic.ob_supplementary_data1 import OBSupplementaryData1

class OBReadProduct2DataProductItemOtherProductType(BaseModel):
    # Description of the Product associated with the account
    description: str = Field(alias='Description')

    # Long name associated with the product
    name: str = Field(alias='Name')

    credit_interest: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeCreditInterest] = Field(None, alias='CreditInterest')

    loan_interest: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeLoanInterest] = Field(None, alias='LoanInterest')

    other_fees_charges: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeOtherFeesCharges] = Field(None, alias='OtherFeesCharges')

    overdraft: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeOverdraft] = Field(None, alias='Overdraft')

    product_details: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeProductDetails] = Field(None, alias='ProductDetails')

    repayment: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeRepayment] = Field(None, alias='Repayment')

    supplementary_data: typing.Optional[OBSupplementaryData1] = Field(None, alias='SupplementaryData')
    class Config:
        arbitrary_types_allowed = True
