# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_repayment_repayment_holiday_item_notes import OBReadProduct2DataProductItemOtherProductTypeRepaymentRepaymentHolidayItemNotes

class OBReadProduct2DataProductItemOtherProductTypeRepaymentRepaymentHolidayItem(BaseModel):
    # The maximum length/duration of a Repayment Holiday
    max_holiday_length: typing.Optional[int] = Field(None, alias='MaxHolidayLength')

    # The unit of period (days, weeks, months etc.) of the repayment holiday
    max_holiday_period: typing.Optional[Literal["PACT", "PDAY", "PHYR", "PMTH", "PQTR", "PWEK", "PYER"]] = Field(None, alias='MaxHolidayPeriod')

    notes: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeRepaymentRepaymentHolidayItemNotes] = Field(None, alias='Notes')
    class Config:
        arbitrary_types_allowed = True
