# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.ob_other_code_type10 import OBOtherCodeType10
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_product_details_notes import OBReadProduct2DataProductItemOtherProductTypeProductDetailsNotes
from open_banking_account_and_transaction_python_sdk.pydantic.ob_read_product2_data_product_item_other_product_type_product_details_segment import OBReadProduct2DataProductItemOtherProductTypeProductDetailsSegment

class OBReadProduct2DataProductItemOtherProductTypeProductDetails(BaseModel):
    # The length/duration of the fee free period
    fee_free_length: typing.Optional[int] = Field(None, alias='FeeFreeLength')

    # The unit of period (days, weeks, months etc.) of the promotional length
    fee_free_length_period: typing.Optional[Literal["PACT", "PDAY", "PHYR", "PMTH", "PQTR", "PWEK", "PYER"]] = Field(None, alias='FeeFreeLengthPeriod')

    # The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
    monthly_maximum_charge: typing.Optional[str] = Field(None, alias='MonthlyMaximumCharge')

    notes: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeProductDetailsNotes] = Field(None, alias='Notes')

    other_segment: typing.Optional[OBOtherCodeType10] = Field(None, alias='OtherSegment')

    segment: typing.Optional[OBReadProduct2DataProductItemOtherProductTypeProductDetailsSegment] = Field(None, alias='Segment')
    class Config:
        arbitrary_types_allowed = True
