# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.ob_balance_type1_code import OBBalanceType1Code
from open_banking_account_and_transaction_python_sdk.pydantic.ob_credit_debit_code2 import OBCreditDebitCode2
from open_banking_account_and_transaction_python_sdk.pydantic.ob_transaction_cash_balance_amount import OBTransactionCashBalanceAmount

class OBTransactionCashBalance(BaseModel):
    amount: OBTransactionCashBalanceAmount = Field(alias='Amount')

    credit_debit_indicator: OBCreditDebitCode2 = Field(alias='CreditDebitIndicator')

    type: OBBalanceType1Code = Field(alias='Type')
    class Config:
        arbitrary_types_allowed = True
