# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_product_details_notes import OBPCAData1ProductDetailsNotes
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_product_details_segment import OBPCAData1ProductDetailsSegment

class OBPCAData1ProductDetails(BaseModel):
    # The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
    monthly_maximum_charge: typing.Optional[str] = Field(None, alias='MonthlyMaximumCharge')

    notes: typing.Optional[OBPCAData1ProductDetailsNotes] = Field(None, alias='Notes')

    segment: typing.Optional[OBPCAData1ProductDetailsSegment] = Field(None, alias='Segment')
    class Config:
        arbitrary_types_allowed = True
