# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_fee_applicable_range import OBPCAData1OtherFeesChargesFeeChargeDetailItemFeeApplicableRange
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_fee_charge_cap import OBPCAData1OtherFeesChargesFeeChargeDetailItemFeeChargeCap
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_notes import OBPCAData1OtherFeesChargesFeeChargeDetailItemNotes
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_other_application_frequency import OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherApplicationFrequency
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_other_calculation_frequency import OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherCalculationFrequency
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_other_fee_category_type import OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeCategoryType
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_other_fee_rate_type import OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeRateType
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges_fee_charge_detail_item_other_fee_type import OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeType

class OBPCAData1OtherFeesChargesFeeChargeDetailItem(BaseModel):
    # How frequently the fee/charge is applied to the account
    application_frequency: Literal["AccountClosing", "AccountOpening", "AcademicTerm", "ChargingPeriod", "Daily", "PerItem", "Monthly", "OnAccountAnniversary", "Other", "PerHour", "PerOccurrence", "PerSheet", "PerTransaction", "PerTransactionAmount", "PerTransactionPercentage", "Quarterly", "SixMonthly", "StatementMonthly", "Weekly", "Yearly"] = Field(alias='ApplicationFrequency')

    # Categorisation of fees and charges into standard categories.
    fee_category: Literal["Other", "Servicing"] = Field(alias='FeeCategory')

    # Fee/Charge Type
    fee_type: Literal["ServiceCAccountFee", "ServiceCAccountFeeMonthly", "ServiceCOther", "Other"] = Field(alias='FeeType')

    # How frequently the fee/charge is calculated
    calculation_frequency: typing.Optional[Literal["AccountClosing", "AccountOpening", "AcademicTerm", "ChargingPeriod", "Daily", "PerItem", "Monthly", "OnAccountAnniversary", "Other", "PerHour", "PerOccurrence", "PerSheet", "PerTransaction", "PerTransactionAmount", "PerTransactionPercentage", "Quarterly", "SixMonthly", "StatementMonthly", "Weekly", "Yearly"]] = Field(None, alias='CalculationFrequency')

    # Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
    fee_amount: typing.Optional[str] = Field(None, alias='FeeAmount')

    fee_applicable_range: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemFeeApplicableRange] = Field(None, alias='FeeApplicableRange')

    fee_charge_cap: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemFeeChargeCap] = Field(None, alias='FeeChargeCap')

    # Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
    fee_rate: typing.Optional[str] = Field(None, alias='FeeRate')

    # Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
    fee_rate_type: typing.Optional[Literal["LinkedBaseRate", "Gross", "Net", "Other"]] = Field(None, alias='FeeRateType')

    notes: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemNotes] = Field(None, alias='Notes')

    other_application_frequency: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherApplicationFrequency] = Field(None, alias='OtherApplicationFrequency')

    other_calculation_frequency: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherCalculationFrequency] = Field(None, alias='OtherCalculationFrequency')

    other_fee_category_type: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeCategoryType] = Field(None, alias='OtherFeeCategoryType')

    other_fee_rate_type: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeRateType] = Field(None, alias='OtherFeeRateType')

    other_fee_type: typing.Optional[OBPCAData1OtherFeesChargesFeeChargeDetailItemOtherFeeType] = Field(None, alias='OtherFeeType')
    class Config:
        arbitrary_types_allowed = True
