# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_overdraft_overdraft_tier_band_set_item_overdraft_fees_charges_item_overdraft_fee_charge_detail_item_overdraft_fee_charge_cap_fee_type import OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapFeeType
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_overdraft_overdraft_tier_band_set_item_overdraft_fees_charges_item_overdraft_fee_charge_detail_item_overdraft_fee_charge_cap_notes import OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapNotes
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_overdraft_overdraft_tier_band_set_item_overdraft_fees_charges_item_overdraft_fee_charge_detail_item_overdraft_fee_charge_cap_other_fee_type import OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapOtherFeeType

class OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCap(BaseModel):
    fee_type: OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapFeeType = Field(alias='FeeType')

    # Indicates that this is the minimum/ maximum fee/charge that can be applied by the financial institution
    min_max_type: Literal["Minimum", "Maximum"] = Field(alias='MinMaxType')

    # Period e.g. day, week, month etc. for which the fee/charge is capped
    capping_period: typing.Optional[Literal["AcademicTerm", "Day", "Half Year", "Month", "Quarter", "Week", "Year"]] = Field(None, alias='CappingPeriod')

    # Cap amount charged for a fee/charge
    fee_cap_amount: typing.Optional[str] = Field(None, alias='FeeCapAmount')

    # fee/charges are captured dependent on the number of occurrences rather than capped at a particular amount
    fee_cap_occurrence: typing.Optional[typing.Union[int, float]] = Field(None, alias='FeeCapOccurrence')

    notes: typing.Optional[OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapNotes] = Field(None, alias='Notes')

    other_fee_type: typing.Optional[OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftFeesChargesItemOverdraftFeeChargeDetailItemOverdraftFeeChargeCapOtherFeeType] = Field(None, alias='OtherFeeType')

    # Specifies for the overdraft control feature/benefit
    overdraft_control_indicator: typing.Optional[bool] = Field(None, alias='OverdraftControlIndicator')
    class Config:
        arbitrary_types_allowed = True
