# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_credit_interest import OBPCAData1CreditInterest
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_other_fees_charges import OBPCAData1OtherFeesCharges
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_overdraft import OBPCAData1Overdraft
from open_banking_account_and_transaction_python_sdk.pydantic.obpca_data1_product_details import OBPCAData1ProductDetails

class OBPCAData1(BaseModel):
    credit_interest: typing.Optional[OBPCAData1CreditInterest] = Field(None, alias='CreditInterest')

    other_fees_charges: typing.Optional[OBPCAData1OtherFeesCharges] = Field(None, alias='OtherFeesCharges')

    overdraft: typing.Optional[OBPCAData1Overdraft] = Field(None, alias='Overdraft')

    product_details: typing.Optional[OBPCAData1ProductDetails] = Field(None, alias='ProductDetails')
    class Config:
        arbitrary_types_allowed = True
