# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.model.ob_read_product2_data_product_item_other_product_type_other_fees_charges_item_fee_charge_cap_item_other_fee_type_item import OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeCapItemOtherFeeTypeItem
from open_banking_account_and_transaction_python_sdk import configuration


class TestOBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeCapItemOtherFeeTypeItem(unittest.TestCase):
    """OBReadProduct2DataProductItemOtherProductTypeOtherFeesChargesItemFeeChargeCapItemOtherFeeTypeItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
