# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.model.obpca_data1_credit_interest_tier_band_set_item_tier_band_item_other_bank_interest_type import OBPCAData1CreditInterestTierBandSetItemTierBandItemOtherBankInterestType
from open_banking_account_and_transaction_python_sdk import configuration


class TestOBPCAData1CreditInterestTierBandSetItemTierBandItemOtherBankInterestType(unittest.TestCase):
    """OBPCAData1CreditInterestTierBandSetItemTierBandItemOtherBankInterestType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
