# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.model.ob_statement2_basic_statement_value_item import OBStatement2BasicStatementValueItem
from open_banking_account_and_transaction_python_sdk import configuration


class TestOBStatement2BasicStatementValueItem(unittest.TestCase):
    """OBStatement2BasicStatementValueItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
