# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.model.obpca_data1_product_details_notes import OBPCAData1ProductDetailsNotes
from open_banking_account_and_transaction_python_sdk import configuration


class TestOBPCAData1ProductDetailsNotes(unittest.TestCase):
    """OBPCAData1ProductDetailsNotes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
