# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.model.obbca_data1_other_fees_charges_item_fee_charge_detail_item_other_fee_category_type import OBBCAData1OtherFeesChargesItemFeeChargeDetailItemOtherFeeCategoryType
from open_banking_account_and_transaction_python_sdk import configuration


class TestOBBCAData1OtherFeesChargesItemFeeChargeDetailItemOtherFeeCategoryType(unittest.TestCase):
    """OBBCAData1OtherFeesChargesItemFeeChargeDetailItemOtherFeeCategoryType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
