# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from open_banking_account_and_transaction_python_sdk.paths.account_access_consents.post import CreateConsentRaw
from open_banking_account_and_transaction_python_sdk.paths.account_access_consents_consent_id.delete import DeleteConsentRaw
from open_banking_account_and_transaction_python_sdk.paths.account_access_consents_consent_id.get import GetConsentRaw


class AccountAccessApiRaw(
    CreateConsentRaw,
    DeleteConsentRaw,
    GetConsentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
