# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from open_banking_account_and_transaction_python_sdk.paths.accounts_account_id.get import Get
from open_banking_account_and_transaction_python_sdk.paths.accounts.get import GetAll
from open_banking_account_and_transaction_python_sdk.apis.tags.accounts_api_raw import AccountsApiRaw


class AccountsApi(
    Get,
    GetAll,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AccountsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AccountsApiRaw(api_client)
