# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from open_banking_account_and_transaction_python_sdk.paths.accounts_account_id_scheduled_payments.get import GetAllRaw
from open_banking_account_and_transaction_python_sdk.paths.scheduled_payments.get import GetAll0Raw


class ScheduledPaymentsApiRaw(
    GetAllRaw,
    GetAll0Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
