# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from open_banking_account_and_transaction_python_sdk.paths.accounts_account_id_statements_statement_id_transactions.get import GetDetailsRaw
from open_banking_account_and_transaction_python_sdk.paths.accounts_account_id_transactions.get import GetDetails0Raw
from open_banking_account_and_transaction_python_sdk.paths.transactions.get import GetDetails1Raw


class TransactionsApiRaw(
    GetDetailsRaw,
    GetDetails0Raw,
    GetDetails1Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
