# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import open_banking_account_and_transaction_python_sdk
from open_banking_account_and_transaction_python_sdk.paths.account_access_consents_consent_id import delete
from open_banking_account_and_transaction_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAccountAccessConsentsConsentId(ApiTestMixin, unittest.TestCase):
    """
    AccountAccessConsentsConsentId unit test stubs
        Delete Account Access Consents
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
