# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from open_banking_account_and_transaction_python_sdk import schemas  # noqa: F401


class OBInterestRateType1Code0(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
    """


    class MetaOapg:
        enum_value_to_name = {
            "INBB": "INBB",
            "INFR": "INFR",
            "INGR": "INGR",
            "INLR": "INLR",
            "INNE": "INNE",
            "INOT": "INOT",
        }
    
    @schemas.classproperty
    def INBB(cls):
        return cls("INBB")
    
    @schemas.classproperty
    def INFR(cls):
        return cls("INFR")
    
    @schemas.classproperty
    def INGR(cls):
        return cls("INGR")
    
    @schemas.classproperty
    def INLR(cls):
        return cls("INLR")
    
    @schemas.classproperty
    def INNE(cls):
        return cls("INNE")
    
    @schemas.classproperty
    def INOT(cls):
        return cls("INOT")
