# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from open_banking_account_and_transaction_python_sdk import schemas  # noqa: F401


class OBBCAData1ProductDetails(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            FeeFreeLength = schemas.Float32Schema
            
            
            class FeeFreeLengthPeriod(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "Day": "DAY",
                        "Half Year": "HALF_YEAR",
                        "Month": "MONTH",
                        "Quarter": "QUARTER",
                        "Week": "WEEK",
                        "Year": "YEAR",
                    }
                
                @schemas.classproperty
                def DAY(cls):
                    return cls("Day")
                
                @schemas.classproperty
                def HALF_YEAR(cls):
                    return cls("Half Year")
                
                @schemas.classproperty
                def MONTH(cls):
                    return cls("Month")
                
                @schemas.classproperty
                def QUARTER(cls):
                    return cls("Quarter")
                
                @schemas.classproperty
                def WEEK(cls):
                    return cls("Week")
                
                @schemas.classproperty
                def YEAR(cls):
                    return cls("Year")
        
            @staticmethod
            def Notes() -> typing.Type['OBBCAData1ProductDetailsNotes']:
                return OBBCAData1ProductDetailsNotes
        
            @staticmethod
            def Segment() -> typing.Type['OBBCAData1ProductDetailsSegment']:
                return OBBCAData1ProductDetailsSegment
            __annotations__ = {
                "FeeFreeLength": FeeFreeLength,
                "FeeFreeLengthPeriod": FeeFreeLengthPeriod,
                "Notes": Notes,
                "Segment": Segment,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FeeFreeLength"]) -> MetaOapg.properties.FeeFreeLength: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["FeeFreeLengthPeriod"]) -> MetaOapg.properties.FeeFreeLengthPeriod: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Notes"]) -> 'OBBCAData1ProductDetailsNotes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Segment"]) -> 'OBBCAData1ProductDetailsSegment': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["FeeFreeLength", "FeeFreeLengthPeriod", "Notes", "Segment", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FeeFreeLength"]) -> typing.Union[MetaOapg.properties.FeeFreeLength, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["FeeFreeLengthPeriod"]) -> typing.Union[MetaOapg.properties.FeeFreeLengthPeriod, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Notes"]) -> typing.Union['OBBCAData1ProductDetailsNotes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Segment"]) -> typing.Union['OBBCAData1ProductDetailsSegment', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["FeeFreeLength", "FeeFreeLengthPeriod", "Notes", "Segment", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        FeeFreeLength: typing.Union[MetaOapg.properties.FeeFreeLength, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        FeeFreeLengthPeriod: typing.Union[MetaOapg.properties.FeeFreeLengthPeriod, str, schemas.Unset] = schemas.unset,
        Notes: typing.Union['OBBCAData1ProductDetailsNotes', schemas.Unset] = schemas.unset,
        Segment: typing.Union['OBBCAData1ProductDetailsSegment', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OBBCAData1ProductDetails':
        return super().__new__(
            cls,
            *args,
            FeeFreeLength=FeeFreeLength,
            FeeFreeLengthPeriod=FeeFreeLengthPeriod,
            Notes=Notes,
            Segment=Segment,
            _configuration=_configuration,
            **kwargs,
        )

from open_banking_account_and_transaction_python_sdk.model.obbca_data1_product_details_notes import OBBCAData1ProductDetailsNotes
from open_banking_account_and_transaction_python_sdk.model.obbca_data1_product_details_segment import OBBCAData1ProductDetailsSegment
