# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from open_banking_account_and_transaction_python_sdk import schemas  # noqa: F401


class OBPCAData1OtherFeesChargesFeeChargeDetail(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    Other fees/charges details
    """


    class MetaOapg:
        min_items = 1
        
        @staticmethod
        def items() -> typing.Type['OBPCAData1OtherFeesChargesFeeChargeDetailItem']:
            return OBPCAData1OtherFeesChargesFeeChargeDetailItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['OBPCAData1OtherFeesChargesFeeChargeDetailItem'], typing.List['OBPCAData1OtherFeesChargesFeeChargeDetailItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'OBPCAData1OtherFeesChargesFeeChargeDetail':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'OBPCAData1OtherFeesChargesFeeChargeDetailItem':
        return super().__getitem__(i)

from open_banking_account_and_transaction_python_sdk.model.obpca_data1_other_fees_charges_fee_charge_detail_item import OBPCAData1OtherFeesChargesFeeChargeDetailItem
