# coding: utf-8

"""
    Account and Transaction API Specification

    Swagger for Account and Transaction API Specification

    The version of the OpenAPI document: 3.1.7
    Contact: ServiceDesk@openbanking.org.uk
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from open_banking_account_and_transaction_python_sdk import schemas  # noqa: F401


class ProprietaryBankTransactionCodeStructure1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Set of elements to fully identify a proprietary bank transaction code.
    """


    class MetaOapg:
        required = {
            "Code",
        }
        
        class properties:
            
            
            class Code(
                schemas.StrSchema
            ):
                pass
            
            
            class Issuer(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "Code": Code,
                "Issuer": Issuer,
            }
    
    Code: MetaOapg.properties.Code
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Code"]) -> MetaOapg.properties.Code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Issuer"]) -> MetaOapg.properties.Issuer: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Code", "Issuer", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Code"]) -> MetaOapg.properties.Code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Issuer"]) -> typing.Union[MetaOapg.properties.Issuer, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Code", "Issuer", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Code: typing.Union[MetaOapg.properties.Code, str, ],
        Issuer: typing.Union[MetaOapg.properties.Issuer, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ProprietaryBankTransactionCodeStructure1':
        return super().__new__(
            cls,
            *args,
            Code=Code,
            Issuer=Issuer,
            _configuration=_configuration,
            **kwargs,
        )
